INFO:root:Exception extract_data_1 main
ERROR:root:HTTP Error 404: 
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_data_1.py", line 99, in <module>
    main()
  File "/home/runner/work/stocks/stocks/extract_data_1.py", line 89, in main
    data.append(f.get_levermann_data(row, df_index_hist, df_index_prices, DATES, qrt_date, jv_date))
  File "/home/runner/work/stocks/stocks/functions.py", line 169, in get_levermann_data
    df_eps = dat.eps_trend
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/ticker.py", line 290, in eps_trend
    return self.get_eps_trend()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/base.py", line 372, in get_eps_trend
    data = self._analysis.eps_trend
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 67, in eps_trend
    self._eps_trend = self._get_periodic_df('epsTrend')
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 35, in _get_periodic_df
    self._fetch_earnings_trend()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 188, in _fetch_earnings_trend
    data = self._fetch(['earningsTrend'])
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 180, in _fetch
    result = self._data.get_raw_json(_QUOTE_SUMMARY_URL_ + f"/{self._symbol}", user_agent_headers=self._data.user_agent_headers, params=params_dict)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/data.py", line 405, in get_raw_json
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/curl_cffi/requests/models.py", line 155, in raise_for_status
    raise HTTPError(f"HTTP Error {self.status_code}: {self.reason}", 0, self)
curl_cffi.requests.exceptions.HTTPError: HTTP Error 404: 
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_data_1.py", line 102, in <module>
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception extract_data_2 main
ERROR:root:HTTP Error 404: 
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_data_2.py", line 99, in <module>
    main()
  File "/home/runner/work/stocks/stocks/extract_data_2.py", line 77, in main
    data.append(f.get_levermann_data(row, df_index_hist, df_index_prices, DATES, qrt_date, jv_date))
  File "/home/runner/work/stocks/stocks/functions.py", line 169, in get_levermann_data
    df_eps = dat.eps_trend
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/ticker.py", line 290, in eps_trend
    return self.get_eps_trend()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/base.py", line 372, in get_eps_trend
    data = self._analysis.eps_trend
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 67, in eps_trend
    self._eps_trend = self._get_periodic_df('epsTrend')
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 35, in _get_periodic_df
    self._fetch_earnings_trend()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 188, in _fetch_earnings_trend
    data = self._fetch(['earningsTrend'])
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/scrapers/analysis.py", line 180, in _fetch
    result = self._data.get_raw_json(_QUOTE_SUMMARY_URL_ + f"/{self._symbol}", user_agent_headers=self._data.user_agent_headers, params=params_dict)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/yfinance/data.py", line 405, in get_raw_json
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/curl_cffi/requests/models.py", line 155, in raise_for_status
    raise HTTPError(f"HTTP Error {self.status_code}: {self.reason}", 0, self)
curl_cffi.requests.exceptions.HTTPError: HTTP Error 404: 
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_data_2.py", line 102, in <module>
    logging.error(err, stack_info=True, exc_info=True)
ERROR:yfinance:$C79.AX: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:Failed to get ticker 'CNE1000029Z6.SG' reason: Failed to perform, curl: (16) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:$ERG.MI: possibly delisted; no price data found  (period=2y)
INFO:root:Exception depot manager update data: 1 YALA
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 2 MUR.WA
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 3 SSAB-B.ST
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 4 SEM.LS
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 5 EVS.BR
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 6 ALK.AX
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
INFO:root:Exception depot manager update data: 7 GF.MI
ERROR:root:local variable 'cur_exr' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 66, in main
    f.update_depot(df_depot, row, cur_time)
  File "/home/runner/work/stocks/stocks/functions.py", line 588, in update_depot
    cur_exr = update_exr(cur_exr, cur_currency)
UnboundLocalError: local variable 'cur_exr' referenced before assignment
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 202, in <module>
    main()
  File "/home/runner/work/stocks/stocks/depot_mgt.py", line 70, in main
    logging.error(err, stack_info=True, exc_info=True)
ERROR:yfinance:Failed to get ticker 'CASC.CN' reason: Expecting value: line 1 column 1 (char 0)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-04 -> 2025-05-10)
INFO:root:Exception extract_isin main
ERROR:root:'name_finanzen'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name_finanzen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_isin.py", line 132, in <module>
    main()
  File "/home/runner/work/stocks/stocks/extract_isin.py", line 113, in main
    df_fin_links['kgv_old_url'] = BASE_URL + "bilanz_guv/" + df_fin_links['name_finanzen']
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'name_finanzen'
Stack (most recent call last):
  File "/home/runner/work/stocks/stocks/extract_isin.py", line 135, in <module>
    logging.error(err, stack_info=True, exc_info=True)
ERROR:yfinance:$MTD: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$AC: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:Failed to get ticker 'CA05453A2074.SG' reason: Failed to perform, curl: (28) Operation timed out after 10002 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:$SPGI: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:Failed to get ticker 'WSTEP.OL' reason: Failed to perform, curl: (16) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:Failed to get ticker 'PGE.V' reason: Failed to perform, curl: (28) Operation timed out after 10002 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:$LLYVA: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-06 -> 2025-05-12)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-07 -> 2025-05-13)
ERROR:yfinance:Failed to get ticker '2105.HK' reason: Failed to perform, curl: (16) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-08 -> 2025-05-14)
ERROR:yfinance:Failed to get ticker 'M5Z.F' reason: Failed to perform, curl: (16) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-09 -> 2025-05-15)
ERROR:yfinance:$GSBD: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-10 -> 2025-05-16)
ERROR:yfinance:$GGG-H.V: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$GGG-H.V: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$CNE100002BG6.SG: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=2y)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$RCWLY: possibly delisted; no price data found  (1d 1926-06-13 -> 2025-05-19)
